//
//  GetLocationRequest.swift
//  WhyCookIn
//
//  Created by Joowon Jang on 12/22/24.
//
//  geolocation
//  <br/>https://ncloud.apigw.ntruss.com/geolocation/v2
//
//  OpenAPI spec version: 2018-07-04T02:49:01Z
//
//  NOTE: This class is auto generated by the swagger code generator program.
//  https://github.com/swagger-api/swagger-codegen.git
//  Do not edit the class manually.
//

import Foundation

/// GetLocationRequest
///
/// 인코딩(enc), 추가정보포함여부(ext), IP 주소(ip), 응답 형식(responseFormatType)
///
/// In the Java version, it had fields and relevant getters/setters. In Swift, we usually pass
/// these as query parameters, so you might not strictly need to store them all in a struct.
/// But if you’d like to keep them for reference, here they are.
struct GetLocationRequest {
    /// 인코딩 (예: "utf-8")
    var enc: String?
    
    /// 추가정보포함여부
    var ext: String?
    
    /// IP 주소
    var ip: String
    
    /// responseFormatType { json, xml }
    var responseFormatType: String?
}
