//
//  GetLocationResponse.swift
//  WhyCookIn
//
//  Created by Joowon Jang on 12/22/24.
//
//  geolocation
//  <br/>https://ncloud.apigw.ntruss.com/geolocation/v2
//
//  OpenAPI spec version: 2018-07-04T02:49:01Z
//
//  NOTE: This class is auto generated by the swagger code generator program.
//  https://github.com/swagger-api/swagger-codegen.git
//  Do not edit the class manually.
//

import Foundation

/// GetLocationResponse
///
/// - requestId
/// - returnCode
/// - returnMessage
/// - geoLocation
///
/// This is the response body you get from Ncloud's geolocation API.
struct GetLocationResponse: Codable {
    /// original Java doc: Get requestId
    let requestId: String?
    
    /// original Java doc: Get returnCode
    let returnCode: String?
    
    /// original Java doc: Get returnMessage
    let returnMessage: String?
    
    /// geoLocation object
    let geoLocation: GeoLocation?
}
